## Chapter 2- Linear Algebra

* linear algebra is a form of continuous rather thandiscrete mathematics
* **scalar** - single number
	* matrix with only one entry
	* a scalar is its own transpose
* **vector** - array of numbers
	* think of vectors as identifying points in space, with each elementgiving the coordinate along a different axis
	* matrix with only one column
* **matrix** - a 2-D array of numbers
	* can add matrices of same shape by just adding each element i,j
	* can multiply matrix by scalar
	* can add vector to a matrix, add the vector to each row of the matrix
	* broadcasting - copying a vector to many locations like in adding to a matrix
* **tensor** - an array with more than two axes
* **transpose** - mirror image of the matrix across a diagonal line, called the main diagonal
* $(A^T)_{i,j}$ = $A_{j,i}$
* **element-wise (Hadamard) product** - $\odot$ results in a matrix with the product of the individual elements

In [43]:
import numpy as np

# multiplying a 2x3 matrix by a 3x2 matrix produces a 2x2 matrix
np.dot([[1,2,3],[4,5,6]], [[1,2],[3,4],[5,6]])

array([[22, 28],
       [49, 64]])

* matrix multiplication / dot product ($\cdot$) is:
	* distributive: A(B + C) = AB + AC
	* associative: A(BC) = (AB)C
	* NOT commutative, i.e. AB != BA, 
    * however dot product b/t two vectors is commutative: $X^TY$ = $Y^TX$
* Transpose of a matrix product: $(AB)^T$ = $B^TA^T$
* Matrix inverse of $A$ is $A^{-1}$
* $A^{-1}A = I$
* $A^{-1}$ is primarily a theoretical tool
* **column space** of a matrix is number of columns that are linearly independent (e.g., two columns with the same values count as only one column in column space)
* Dimensionality of the column space - The number of rows / cases must be greater than or equal to the number of linearly independent columns.
* **linear independence** - a set of vectors is linearly independent if no vector in the set is a linear combination of the other vectors
* For the column space of the matrix to encompass all of $\mathbb{R}^m$, the matrix must contain at least one set of $m$ linearly independent columns. This condition is both necessary and sufficient for the equation $Ax = b$ to have a solution forevery value of $b$.
* **singular matrix** - a square matrix with linearly dependent columns
* **scalar matrix** - a square diagonal matrix with all its main diagonal entries equal

### 2.5 Norms

* Euclidian Norm - $L^2$ norm - $||x||_2$
* Used so often in ML sometimes just written $||x||$ without the subscript 2
* The norm of a vector $x$ measures the distance from the origin to the point $x$

In [35]:

p = 2 # L2 norm
x = np.array([-1,2,3])
# one way to get L2 Norm
np.linalg.norm(x, ord=p)

3.7416573867739413

In [36]:
# another way
sum([y ** p for y in x])**(1/p)

3.7416573867739413

In [37]:
# yet another way is just x transpose * x:

sum(x.T * x) ** (1/p)

3.7416573867739413

* Squared $L^2$ norm is actually easier to work with than the actual $L^2$ norm, because each derivative of thesquared $L^2$ norm with respect to each element of $x$ depends only on the corresponding element of $x$, while all the derivatives of the $L^2$ norm depend on the entire vector
    * This isn't desirable sometimes as it increases super slowly around 0, and we're interested in things are are small but nonzero, so in these cases we turn to the $L^1$ norm, which is just the sum of the aboslute values of the elements in the vector:

$||x||_1 =\sum_i |x_i|$

* $L^1$ norm is commonly used in machine learning when the difference between zero and nonzero elements is very important

In [40]:
p = 1 # L1 norm
x = np.array([-1,2,3])
# one way to get L2 Norm
np.linalg.norm(x, ord=p)

6.0

* **max norm** - $L^\infty$ norm - absolute value of the element with the largest magnitude in the vector
* **Frobenius norm** - measures the size of a matrix, analogous to the $L^2$ norm for a vector

In [51]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [53]:
# Frobenius norm of a
np.linalg.norm(a, 'fro')

9.539392014169456

In [63]:
# Frobenius norm of b is the same because elements of the matrix are the same
np.linalg.norm(b, 'fro')

9.539392014169456

The dot product of two vectors can be rewritten in terms of norms. Specifically,

$x^Ty = ||x||_2 ||y||_2 cos\theta$

where $\theta$ is the angle between the two vectors

### 2.6 Special Kinds of Matrices and Vectors

* **diagonal matrix** - 0's everywhere but on the diagonal.  All identity matrices are diagonal matrices
* to compute $diag(v)x$, we only need to scale each element $x_i$ by $v_i$. In other words:

$diag(v)x=v \odot x$

* inverse of a square diagonal matrix exists if all diagonal elements are non-zero
* if this is true, the inverse is another square diagonal matrix, where each value $v_i$ in the diagonal becomes $\frac{1}{v_i}$

In [64]:
square_diagonal = np.array([[1,0,0,0], [0,5,0,0], [0,0,8,0], [0,0,0,10]])
square_diagonal

array([[ 1,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0,  8,  0],
       [ 0,  0,  0, 10]])

In [62]:
np.linalg.inv(square_diagonal)

array([[1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.2  , 0.   , 0.   ],
       [0.   , 0.   , 0.125, 0.   ],
       [0.   , 0.   , 0.   , 0.1  ]])

* **symmetric matrix** - any matrix that is equal to its own transpose, e.g., $A = A^T$

In [71]:
rectangular_diagonal1 = np.array([[1,0,0,0], [0,2,0,0], [0,0,3,0]])
rectangular_diagonal1

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [70]:
rectangular_diagonal1 * 2

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0]])

* **unit vector** - vector with **unit norm** $||x||_2 = 1$
* Two vectors are **orthogonal** to each other if $x^Ty = 0$
    * Also means they're at right angles to each other
    * If they're orthogonal and of unit length we say they're **orthonormal**
* An **orthogonal matrix** is a square matrix whose **rows** are mutually orthonormal **and** whose **columns** are mutually orthonormal:

$$A^TA = AA^T = I$$

* NOTE: rows are not merely orthogonal but **fully orthonormal**

### 2.7 Eigendecomposition

* **eigendecomposition** - where we decompose a matrix into a set of eigenvectors and eigenvalues
* **eigenvector** of a square matrix is a nonzero vector $v$ such that multiplication by $A$ modifies only the scale of $v$ - $Av = \lambda V$
* $\lambda$ is a scalar known as the **eigenvalue** corresponding to the eigenvector
* usually look only for unit eigenvectors
* We can make a matrix with one eigenvector per column: $V$ = $v^{(1)}$ ... $v^{(n)}$
* And also a separate vector for all the eigenvectors $\lambda = \lambda_1 ... \lambda_n$
* **eigendecomposition** is then given by: $A = V diag(\lambda)V^{-1}$
* Decomposing matrices into their eigenvalues and eigenvectors can help us analyze certain properties of the matrix, much as decomposing an integer into its prime factors can help us understand the behavior of that integer
* A matrix is singular ONLY if at least one of the eigenvalues is zero
* **positive definite** - all eigenvalues are positive
* **positive semidefinite** - all eigenvalues are >= 0
* **negative definite** - all eigenvalues are negative
* **negative semidefinite**  - all eigenvalues are <= 0

### 2.8 Singular Value Decomposition

* singular value decomposition (SVD) provides another way to factorize a matrix, into **singular vectors** and **singular values**.
* every real matrix has a SVD, but not necessarily an eigenvalue decomposition
    * e.g., non-square matrices don't have an eigenvalue decomposition, need to do SVD instead
* **eigendecomposition**: $A = V diag(\lambda)V^{-1}$
* **SVD**:  $A = UDV^T$ where
    * $A$ is an m x n matrix
    * $U$ is an m x m matrix and is orthogonal and its columns are **left-singular vectors**
    * $D$ is an m x n matrix and is diagonal (but not necessarily square) where the elements on the diagonal are the **singular values** of $A$
    * $V$ is an n x n matrix and is orthogonal and its columns are **right-singular vectors**

### 2.9 The Moore-Penrose Pseudoinverse

* When looking for an inverse of a nonsquare matrix:
    * If a matrix is taller than it is wide, it's possible there's no solution
    * If a matrix is wider than it is tall, it's possible that there are multiple solutions
* Reread this, not sticking at the moment

### 2.10 The Trace Operator

* Gives the sum of all diagonal entries of a matrix
* Even if two matrices are m x n and n x m: $Tr(AB) = Tr(BA)$ even though the shape of the result of the dot product of $AB$ would be different than the shape of $BA$ (provided m != n)
* A scalar is its own trace

### 2.11 The Determinant

* **the determinant** is equal to the product of all the eigenvalues in a matrix
* Think of it "as a measure of how much multiplication by the matrix expands or contracts space"
    * If $det(A)$ is 0, space is completely contracted along at least one dimension
    * If $det(A)$ is 1, transformation preserves the volume

### 2.12 Example: Principal Components Analysis

* PCA can be derived with only linear algebra
* Uses the $L^2$ norm